services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /docker/appdata/jellyfin:/config
      - /data:/media
      - /transcodes:/transcodes
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Australia/Sydney
      - PLEX_PASS=no
    volumes:
      - /docker/appdata/plex:/config
      - /data:/media
      - /transcodes:/transcodes
    ports:
      - "32400:32400"
