services:
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 8080:8080 # qBittorrent web UI
      - 8085:8085 # SABnzbd web UI
      - 9001:9001 # qBittorrent embedded tracker port
      - 50533:50533 # qBittorrent incoming connections
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-r\d+-ls\d+$$
      - wud.tag.transform=^(\d+\.\d+\.\d+)-(r\d+)-(ls\d+)$$ => $$1+$$3-$$2
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:release
    network_mode: service:wireguard
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
      - ARGS=--server 0.0.0.0:8085
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /data/downloads/usenet:/data/downloads/usenet:rw
    restart: always
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+$$
      - wud.tag.transform=^release-(\d+\.\d+\.\d+)$$ => $$1
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release
    network_mode: service:wireguard
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /data/downloads/torrents:/data/downloads/torrents:rw
    restart: always
    labels:
      - wud.tag.include=^legacy-\d+\.\d+\.\d+$$
      - wud.tag.transform=^legacy-(\d+\.\d+\.\d+)$$ => $$1
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:release
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
      - /data:/data
    ports:
      - 9696:9696
    restart: always
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+\.\d+$$
      - wud.tag.transform=^release-(\d+\.\d+\.\d+)\.(\d+)$$ => $$1-$$2
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: always
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+\.\d+$$
      - wud.tag.transform=^release-(\d+\.\d+\.\d+)\.(\d+)$$ => $$1-$$2
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:release
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: always
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+\.\d+$$
      - wud.tag.transform=^release-(\d+\.\d+\.\d+)\.(\d+)$$ => $$1-$$2
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:release
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data:/data
    ports:
      - 6767:6767
    restart: always
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+$$
      - wud.tag.transform=^release-(\d+\.\d+\.\d+)$$ => $$1
  bookshelf:
    container_name: bookshelf
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bookshelf:/config
      - /data:/data
    ports:
      - 8787:8787
    restart: always
    labels:
      - wud.tag.include=^hardcover-v\d+\.\d+\.\d+\.\d+$$
      - wud.tag.transform=^hardcover-v(\d+\.\d+\.\d+)\.(\d+)$$ => $$1-$$2
  calibre:
    container_name: calibre
    image: linuxserver/calibre
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/calibre:/config
      - /data:/data
    ports:
      - 8180:8080
      - 8181:8181
      - 8182:8081
    shm_size: "1gb"
    restart: always
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+-ls\d+$$
      - wud.tag.transform=^v(\d+\.\d+\.\d+)-(ls\d+)$$ => $$1+$$2
  ombi:
    container_name: ombi
    image: linuxserver/ombi
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/ombi:/config
    ports:
      - 3579:3579
    restart: always
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+-ls\d+$$
      - wud.tag.transform=^v(\d+\.\d+\.\d+)-(ls\d+)$$ => $$1+$$2
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Australia/Sydney
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: always
    labels:
      - wud.tag.include=^v\d+\.\d+\.\d+-ls\d+$$
      - wud.tag.transform=^v(\d+\.\d+\.\d+)-(ls\d+)$$ => $$1+$$2
  uptime_kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-beta\.\d+$$
      - wud.tag.transform=^(\d+\.\d+\.\d+)-beta\.(\d)+$$ => $$1-$$2
  whatsupdocker:
    container_name: wud
    image: getwud/wud
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/wud:/store
      - /docker/docker-compose.yml:/docker/docker-compose.yml
    ports:
      - 3000:3000
    environment:
      - WUD_TRIGGER_DOCKERCOMPOSE_MEDIA_FILE=/docker/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_MEDIA_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_MEDIA_THRESHOLD=minor
      - WUD_TRIGGER_DISCORD_MEDIA_URL=${WUD_TRIGGER_DISCORD_MEDIA_URL}
    restart: always
